name: Configure Terraform backend.
description: Composite action to create the terraform backend configuration file.

inputs:
  backend_bucket:
    description: Name of the bucket serving as the backend.
    required: true
  backend_dynamo:
    description: Name of the DynamoDB used for terraform lock.
    required: true
  aws_region:
    description: The AWS region where the resources are located.
    required: true
  working-directory:
    required: true
    description: wd

runs:
  using: "composite"
  steps:
    - name: Get the resource
      id: resource
      run: |
        cat > ${{inputs.working-directory}}/backend.tf << EOF
          terraform {
            backend "s3" {
              bucket         = "${{inputs.backend_bucket}}"
              dynamodb_table = "${{inputs.backend_dynamo}}"
              key            = "${{github.repository}}/terraform.tfstate"
              region         = "${{inputs.aws_region}}"
            }
          }
        EOF
      shell: bash